ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB*

USER_LIB_PATH += /home/knight/sketchbook/libraries
ARDUINO_LIBS += PID
ARDUINO_LIBS += ros_lib

BOARD_TAG = mega2560 

include /usr/share/arduino/Arduino.mk

